### ISSUE TITLE
search in repositories tags

### ISSUE THREAD

**Issue by mehrdadrad** [SAP/project-portal-for-innersource#11]
It would be great if the search supports tags as well!

**Comment by spier** [comment]
Good idea. Just to double check that I understand it correctly, do you mean the thing that GitHub calls **topics**? (see screenshot based on this repo here)

![topics_example](https://user-images.githubusercontent.com/163029/105214745-afcea980-5b50-11eb-8e18-19e1057bdfb2.JPG)

**Comment by mehrdadrad** [comment]
@spier yes exactly.

**Comment by spier** [comment]
Great, thanks.

Did you confirm that the tool does indeed not consider the topics when searching?
I tried to verify what you said in the [demo](https://sap.github.io/project-portal-for-innersource/index.html#display=card) but couldn't because that contains just test data and no real repos.
Are you running your own instance of this with your own data or similar?

Just wondering how to describe the current and desired behavior in the most specific way, in case somebody wants to pick this up and implement it.

**Comment by mehrdadrad** [comment]
Confirmed, I tried an instance which another group installed and noticed it doesn't care about topics. 
I think topics are great keywords that they should be considered. (enhancing search feature)

**Comment by Michadelic** [comment]
Great idea, unfortunately topics are not included in the GitHub repository search response so we need to change the crawler logic to include topics as well. They could be fetched with a separate call for each repository and merged with the metadata as `topics` in the resulting `repos.json` JSON file:
https://docs.github.com/en/rest/reference/repos#get-all-repository-topics

``` json
{
  "name": "repository",
   ...
   "topics": [
       "octocat",
       "atom",
       "electron",
       "api"
   }
}
```

Including topics in the search should be easy once this is done.
Feel free to contribute this feature.

Kind Regards,
Michael

**Comment by Michadelic** [comment]
great contribution, thank you @spier !

**Comment by Michadelic** [comment]
@spier i updated the documentation as well, kindly check my PR #13

**Comment by Michadelic** [comment]
All done 🏁
