### ISSUE TITLE
Mention existing crawler implementations

### ISSUE THREAD

**Issue by dellagustin-sap** [SAP/project-portal-for-innersource#21]
I found this crawler implementation: https://github.com/zkoppert/innersource-crawler
It would be nice to mention it and maybe add a comment on the contributing guidelines for people to send PRs with a link if they implement a crawler.

**Comment by zkoppert** [comment]
see work happening at https://github.com/SAP/project-portal-for-innersource/pull/18

**Comment by spier** [comment]
More motivation to finish continue work on that PR :)

**Comment by spier** [comment]
@JustinGOSSES @zkoppert in the meantime we got around to create dedicated documentation about the Crawling process. I am sure it would greatly benefit from your review, as you have looked into the crawling topic already. See:
https://github.com/SAP/project-portal-for-innersource/blob/main/docs/CRAWLING.md

Cheers :)

**Comment by Michadelic** [comment]
fixed with #18

**Comment by JustinGOSSES** [comment]
Read through it and seemed very understandable.

Only think of a few small additions that might be useful ....and are more future additions than blockers (1) a reference way to combine results from multiple crawlers running against different code platforms (2) what happens if a code repository exists on multiple code platforms scanned (3) a GitLab to GitHub mapping of the key:value pairs that come out of crawlers. (4) add link to a suitable GitLab crawler once one exists.

Most of these points are for a large distributed organization that might have many internal GitHubs and GitLabs.

**Comment by spier** [comment]
Thanks for the review @JustinGOSSES.

Can you say more about this point 
> (3) a GitLab to GitHub mapping of the key:value pairs that come out of crawlers.

What would this be used for? Is it related to writing a dedicated Gitlab crawler (point 4)?
